/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about a channel related to the ticket suggestion.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel {
    /**
     * The channel id.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel
     */
    id?: number;
    /**
     * The channel-specific ticket name, set if the channel is configured to override the default
     * product name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel
     */
    ticketName?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ticketName': !exists(json, 'ticketName') ? undefined : json['ticketName'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ticketName': value.ticketName,
    };
}

