/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the coordinates
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel {
    /**
     * The latitude of this position (WGS84).
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel
     */
    latitude?: number;
    /**
     * The longitude of this position (WGS84).
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel
     */
    longitude?: number;
    /**
     * The elevation of this position (WGS84).
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel
     */
    elevation?: number | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'elevation': !exists(json, 'elevation') ? undefined : json['elevation'],
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'elevation': value.elevation,
    };
}

