/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsTimeValidityType } from './VTApiPlaneraResaWebV4ModelsTimeValidityType';
import {
    VTApiPlaneraResaWebV4ModelsTimeValidityTypeFromJSON,
    VTApiPlaneraResaWebV4ModelsTimeValidityTypeFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsTimeValidityTypeToJSON,
} from './VTApiPlaneraResaWebV4ModelsTimeValidityType';
import type { VTApiPlaneraResaWebV4ModelsTimeValidityUnit } from './VTApiPlaneraResaWebV4ModelsTimeValidityUnit';
import {
    VTApiPlaneraResaWebV4ModelsTimeValidityUnitFromJSON,
    VTApiPlaneraResaWebV4ModelsTimeValidityUnitFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsTimeValidityUnitToJSON,
} from './VTApiPlaneraResaWebV4ModelsTimeValidityUnit';

/**
 * Information about the time validity of a ticket suggestion.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel {
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsTimeValidityType}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    type?: VTApiPlaneraResaWebV4ModelsTimeValidityType;
    /**
     * The amount of the unit specified by the Unit property. Always used together with the Unit property.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    amount?: number | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsTimeValidityUnit}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    unit?: VTApiPlaneraResaWebV4ModelsTimeValidityUnit;
    /**
     * The from date of a date interval specified in RFC 3339 format. Always used together with the
     * ToDate property.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    fromDate?: string | null;
    /**
     * The to date of a date interval specified in RFC 3339 format. Always used together with the
     * FromDate property.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    toDate?: string | null;
    /**
     * The from time of a datetime interval specified in RFC 3339 format. Always used together with
     * the ToDateTime property.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    fromDateTime?: string | null;
    /**
     * The to time of a datetime interval specified in RFC 3339 format. Always used together with
     * the FromDateTime property.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel
     */
    toDateTime?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : VTApiPlaneraResaWebV4ModelsTimeValidityTypeFromJSON(json['type']),
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'unit': !exists(json, 'unit') ? undefined : VTApiPlaneraResaWebV4ModelsTimeValidityUnitFromJSON(json['unit']),
        'fromDate': !exists(json, 'fromDate') ? undefined : json['fromDate'],
        'toDate': !exists(json, 'toDate') ? undefined : json['toDate'],
        'fromDateTime': !exists(json, 'fromDateTime') ? undefined : json['fromDateTime'],
        'toDateTime': !exists(json, 'toDateTime') ? undefined : json['toDateTime'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': VTApiPlaneraResaWebV4ModelsTimeValidityTypeToJSON(value.type),
        'amount': value.amount,
        'unit': VTApiPlaneraResaWebV4ModelsTimeValidityUnitToJSON(value.unit),
        'fromDate': value.fromDate,
        'toDate': value.toDate,
        'fromDateTime': value.fromDateTime,
        'toDateTime': value.toDateTime,
    };
}

