/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the different types of transport modes.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsTransportMode = {
    Unknown: 'unknown',
    None: 'none',
    Tram: 'tram',
    Bus: 'bus',
    Ferry: 'ferry',
    Train: 'train',
    Taxi: 'taxi',
    Walk: 'walk',
    Bike: 'bike',
    Car: 'car',
    Teletaxi: 'teletaxi'
} as const;
export type VTApiPlaneraResaWebV4ModelsTransportMode = typeof VTApiPlaneraResaWebV4ModelsTransportMode[keyof typeof VTApiPlaneraResaWebV4ModelsTransportMode];


export function VTApiPlaneraResaWebV4ModelsTransportModeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsTransportMode {
    return VTApiPlaneraResaWebV4ModelsTransportModeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsTransportModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsTransportMode {
    return json as VTApiPlaneraResaWebV4ModelsTransportMode;
}

export function VTApiPlaneraResaWebV4ModelsTransportModeToJSON(value?: VTApiPlaneraResaWebV4ModelsTransportMode | null): any {
    return value as any;
}

