/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Deep links to open Padam app with specific trip
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel {
    /**
     * iOS link
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
     */
    ios?: string | null;
    /**
     * Android link
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
     */
    android?: string | null;
    /**
     * Web link
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel
     */
    web?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ios': !exists(json, 'ios') ? undefined : json['ios'],
        'android': !exists(json, 'android') ? undefined : json['android'],
        'web': !exists(json, 'web') ? undefined : json['web'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneysPadamUrlsApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ios': value.ios,
        'android': value.android,
        'web': value.web,
    };
}

