/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel {
    /**
     * The 16-digit Västtrafik gid of the stop point.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
     */
    gid: string;
    /**
     * The stop point name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
     */
    name: string;
    /**
     * The platform of the stop point.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
     */
    platform?: string | null;
    /**
     * The latitude coordinate of the stop point
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
     */
    latitude?: number | null;
    /**
     * The logitude coordinate of the stop point
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel
     */
    longitude?: number | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gid" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': json['gid'],
        'name': json['name'],
        'platform': !exists(json, 'platform') ? undefined : json['platform'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsStopPointApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'name': value.name,
        'platform': value.platform,
        'latitude': value.latitude,
        'longitude': value.longitude,
    };
}

