/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsCoordinateApiModel } from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import {
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';
import type { VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel } from './VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel';
import {
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel';

/**
 * Detailed information about a Public Transport trip leg.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel {
    /**
     * The service journey for the trip leg.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    serviceJourneys?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel> | null;
    /**
     * The calls on the trip leg.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    callsOnTripLeg?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel> | null;
    /**
     * The coordinates for the trip leg.
     * @type {Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    tripLegCoordinates?: Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel> | null;
    /**
     * The tariff zones that the trip leg traverses.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    tariffZones?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel> | null;
    /**
     * Flag indicating if the trip leg is cancelled.
     * @type {boolean}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    isCancelled?: boolean;
    /**
     * Flag indicating if the trip leg is partially cancelled.
     * @type {boolean}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    isPartCancelled?: boolean;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    occupancy?: VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel;
    /**
     * Index of Leg in Journey
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel
     */
    journeyLegIndex?: number;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serviceJourneys': !exists(json, 'serviceJourneys') ? undefined : (json['serviceJourneys'] === null ? null : (json['serviceJourneys'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSON)),
        'callsOnTripLeg': !exists(json, 'callsOnTripLeg') ? undefined : (json['callsOnTripLeg'] === null ? null : (json['callsOnTripLeg'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSON)),
        'tripLegCoordinates': !exists(json, 'tripLegCoordinates') ? undefined : (json['tripLegCoordinates'] === null ? null : (json['tripLegCoordinates'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON)),
        'tariffZones': !exists(json, 'tariffZones') ? undefined : (json['tariffZones'] === null ? null : (json['tariffZones'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON)),
        'isCancelled': !exists(json, 'isCancelled') ? undefined : json['isCancelled'],
        'isPartCancelled': !exists(json, 'isPartCancelled') ? undefined : json['isPartCancelled'],
        'occupancy': !exists(json, 'occupancy') ? undefined : VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSON(json['occupancy']),
        'journeyLegIndex': !exists(json, 'journeyLegIndex') ? undefined : json['journeyLegIndex'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serviceJourneys': value.serviceJourneys === undefined ? undefined : (value.serviceJourneys === null ? null : (value.serviceJourneys as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelToJSON)),
        'callsOnTripLeg': value.callsOnTripLeg === undefined ? undefined : (value.callsOnTripLeg === null ? null : (value.callsOnTripLeg as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelToJSON)),
        'tripLegCoordinates': value.tripLegCoordinates === undefined ? undefined : (value.tripLegCoordinates === null ? null : (value.tripLegCoordinates as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON)),
        'tariffZones': value.tariffZones === undefined ? undefined : (value.tariffZones === null ? null : (value.tariffZones as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON)),
        'isCancelled': value.isCancelled,
        'isPartCancelled': value.isPartCancelled,
        'occupancy': VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelToJSON(value.occupancy),
        'journeyLegIndex': value.journeyLegIndex,
    };
}

