/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information specifying the interval when valid journey information is available, i.e. when it is possible to search journeys.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel {
    /**
     * The start time of the interval when valid journey information is available, specified in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel
     */
    validFrom?: string | null;
    /**
     * The end time of the interval when valid journey information is available, specified in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel
     */
    validUntil?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel {
    return VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validFrom': !exists(json, 'validFrom') ? undefined : json['validFrom'],
        'validUntil': !exists(json, 'validUntil') ? undefined : json['validUntil'],
    };
}

export function VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validFrom': value.validFrom,
        'validUntil': value.validUntil,
    };
}

