/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The different kinds of detailed information that could be included in a get departure details request.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType = {
    Servicejourneycalls: 'servicejourneycalls',
    Servicejourneycoordinates: 'servicejourneycoordinates',
    Occupancy: 'occupancy'
} as const;
export type VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType = typeof VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType[keyof typeof VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType];


export function VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType {
    return VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType {
    return json as VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType;
}

export function VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsDepartureDetailsIncludeType | null): any {
    return value as any;
}

