/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver } from './VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver';
import {
    VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSON,
    VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverToJSON,
} from './VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver';
import type { VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation } from './VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation';
import {
    VTApiPlaneraResaWebV4ModelsLinkSegmentOrientationFromJSON,
    VTApiPlaneraResaWebV4ModelsLinkSegmentOrientationFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsLinkSegmentOrientationToJSON,
} from './VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation';

/**
 * Represents a segment of a departure access link, arrival access link or destination link.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel {
    /**
     * Segment name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
     */
    name?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
     */
    maneuver?: VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
     */
    orientation?: VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation;
    /**
     * Description for the maneuver.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
     */
    maneuverDescription?: string | null;
    /**
     * Distance for this segment in meter.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel
     */
    distanceInMeters?: number | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'maneuver': !exists(json, 'maneuver') ? undefined : VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSON(json['maneuver']),
        'orientation': !exists(json, 'orientation') ? undefined : VTApiPlaneraResaWebV4ModelsLinkSegmentOrientationFromJSON(json['orientation']),
        'maneuverDescription': !exists(json, 'maneuverDescription') ? undefined : json['maneuverDescription'],
        'distanceInMeters': !exists(json, 'distanceInMeters') ? undefined : json['distanceInMeters'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneysLinkSegmentApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'maneuver': VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverToJSON(value.maneuver),
        'orientation': VTApiPlaneraResaWebV4ModelsLinkSegmentOrientationToJSON(value.orientation),
        'maneuverDescription': value.maneuverDescription,
        'distanceInMeters': value.distanceInMeters,
    };
}

