/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';

/**
 * Information about a service journey.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
    /**
     * 16-digit Västtrafik service journey gid.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    gid?: string | null;
    /**
     * A description of the direction.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    direction?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    directionDetails?: VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    line?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModel;
    /**
     * The coordinates of the service journey.
     * @type {Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    serviceJourneyCoordinates?: Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModel> | null;
    /**
     * All calls on the service journey.
     * @type {Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel
     */
    callsOnServiceJourney?: Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModel> | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': !exists(json, 'gid') ? undefined : json['gid'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'directionDetails': !exists(json, 'directionDetails') ? undefined : VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON(json['directionDetails']),
        'line': !exists(json, 'line') ? undefined : VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelFromJSON(json['line']),
        'serviceJourneyCoordinates': !exists(json, 'serviceJourneyCoordinates') ? undefined : (json['serviceJourneyCoordinates'] === null ? null : (json['serviceJourneyCoordinates'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelFromJSON)),
        'callsOnServiceJourney': !exists(json, 'callsOnServiceJourney') ? undefined : (json['callsOnServiceJourney'] === null ? null : (json['callsOnServiceJourney'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModelFromJSON)),
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyDetailsApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'direction': value.direction,
        'directionDetails': VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON(value.directionDetails),
        'line': VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineDetailsApiModelToJSON(value.line),
        'serviceJourneyCoordinates': value.serviceJourneyCoordinates === undefined ? undefined : (value.serviceJourneyCoordinates === null ? null : (value.serviceJourneyCoordinates as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCoordinateApiModelToJSON)),
        'callsOnServiceJourney': value.callsOnServiceJourney === undefined ? undefined : (value.callsOnServiceJourney === null ? null : (value.callsOnServiceJourney as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsCallDetailsApiModelToJSON)),
    };
}

