/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A subset of LocationType
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType = {
    Stoparea: 'stoparea',
    Stoppoint: 'stoppoint',
    Pointofinterest: 'pointofinterest',
    Metastation: 'metastation'
} as const;
export type VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType = typeof VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType[keyof typeof VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType];


export function VTApiPlaneraResaWebV4ModelsLocationByCoordinatesTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType {
    return VTApiPlaneraResaWebV4ModelsLocationByCoordinatesTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsLocationByCoordinatesTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType {
    return json as VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType;
}

export function VTApiPlaneraResaWebV4ModelsLocationByCoordinatesTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType | null): any {
    return value as any;
}

