/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about ticket validity.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel {
    /**
     * The ticket id.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel
     */
    id?: string | null;
    /**
     * Indicates if the ticket is valid for the journey.
     * @type {boolean}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel
     */
    isValidForJourney?: boolean | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isValidForJourney': !exists(json, 'isValidForJourney') ? undefined : json['isValidForJourney'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketValidityApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'isValidForJourney': value.isValidForJourney,
    };
}

