/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Pagination navigation links.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsPaginationLinks
 */
export interface VTApiPlaneraResaWebV4ModelsPaginationLinks {
    /**
     * Link to the previous results page, if available, otherwise null.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsPaginationLinks
     */
    previous?: string | null;
    /**
     * Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsPaginationLinks
     */
    next?: string | null;
    /**
     * Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsPaginationLinks
     */
    current?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsPaginationLinks interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsPaginationLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSON(json: any): VTApiPlaneraResaWebV4ModelsPaginationLinks {
    return VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsPaginationLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'current': !exists(json, 'current') ? undefined : json['current'],
    };
}

export function VTApiPlaneraResaWebV4ModelsPaginationLinksToJSON(value?: VTApiPlaneraResaWebV4ModelsPaginationLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'previous': value.previous,
        'next': value.next,
        'current': value.current,
    };
}

