/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a level of occupancy.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsOccupancyLevel = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Incomplete: 'incomplete',
    Missing: 'missing',
    Notpublictransport: 'notpublictransport'
} as const;
export type VTApiPlaneraResaWebV4ModelsOccupancyLevel = typeof VTApiPlaneraResaWebV4ModelsOccupancyLevel[keyof typeof VTApiPlaneraResaWebV4ModelsOccupancyLevel];


export function VTApiPlaneraResaWebV4ModelsOccupancyLevelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsOccupancyLevel {
    return VTApiPlaneraResaWebV4ModelsOccupancyLevelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsOccupancyLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsOccupancyLevel {
    return json as VTApiPlaneraResaWebV4ModelsOccupancyLevel;
}

export function VTApiPlaneraResaWebV4ModelsOccupancyLevelToJSON(value?: VTApiPlaneraResaWebV4ModelsOccupancyLevel | null): any {
    return value as any;
}

