/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of area for a set of zones.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsAreaType = {
    None: 'none',
    Standard: 'standard',
    Mini: 'mini',
    Extra: 'extra',
    Leisure: 'leisure'
} as const;
export type VTApiPlaneraResaWebV4ModelsAreaType = typeof VTApiPlaneraResaWebV4ModelsAreaType[keyof typeof VTApiPlaneraResaWebV4ModelsAreaType];


export function VTApiPlaneraResaWebV4ModelsAreaTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsAreaType {
    return VTApiPlaneraResaWebV4ModelsAreaTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsAreaTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsAreaType {
    return json as VTApiPlaneraResaWebV4ModelsAreaType;
}

export function VTApiPlaneraResaWebV4ModelsAreaTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsAreaType | null): any {
    return value as any;
}

