/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel {
    /**
     * The 16-digit Västtrafik gid of the stop area.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel
     */
    gid?: string | null;
    /**
     * The stop area name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel
     */
    name?: string | null;
    /**
     * The latitude of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel
     */
    lat?: number;
    /**
     * The longitude of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel
     */
    _long?: number;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel {
    return VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': !exists(json, 'gid') ? undefined : json['gid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'lat': !exists(json, 'lat') ? undefined : json['lat'],
        '_long': !exists(json, 'long') ? undefined : json['long'],
    };
}

export function VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsStopAreasStopAreaApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'name': value.name,
        'lat': value.lat,
        'long': value._long,
    };
}

