/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about a zone related to the ticket suggestion.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
    /**
     * The zone id.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel
     */
    id?: number;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

