/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsProductTypeEnum } from './VTApiPlaneraResaWebV4ModelsProductTypeEnum';
import {
    VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSON,
    VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsProductTypeEnumToJSON,
} from './VTApiPlaneraResaWebV4ModelsProductTypeEnum';
import type { VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel } from './VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel';
import {
    VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel {
    /**
     * 
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
     */
    ticketName?: string | null;
    /**
     * 
     * @type {Array<VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
     */
    configurations?: Array<VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsProductTypeEnum}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
     */
    productType?: VTApiPlaneraResaWebV4ModelsProductTypeEnum;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel {
    return VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ticketName': !exists(json, 'ticketName') ? undefined : json['ticketName'],
        'configurations': !exists(json, 'configurations') ? undefined : (json['configurations'] === null ? null : (json['configurations'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSON)),
        'productType': !exists(json, 'productType') ? undefined : VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSON(json['productType']),
    };
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ticketName': value.ticketName,
        'configurations': value.configurations === undefined ? undefined : (value.configurations === null ? null : (value.configurations as Array<any>).map(VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelToJSON)),
        'productType': VTApiPlaneraResaWebV4ModelsProductTypeEnumToJSON(value.productType),
    };
}

