/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsDateTimeRelatesToType = {
    Departure: 'departure',
    Arrival: 'arrival'
} as const;
export type VTApiPlaneraResaCoreModelsDateTimeRelatesToType = typeof VTApiPlaneraResaCoreModelsDateTimeRelatesToType[keyof typeof VTApiPlaneraResaCoreModelsDateTimeRelatesToType];


export function VTApiPlaneraResaCoreModelsDateTimeRelatesToTypeFromJSON(json: any): VTApiPlaneraResaCoreModelsDateTimeRelatesToType {
    return VTApiPlaneraResaCoreModelsDateTimeRelatesToTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsDateTimeRelatesToTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsDateTimeRelatesToType {
    return json as VTApiPlaneraResaCoreModelsDateTimeRelatesToType;
}

export function VTApiPlaneraResaCoreModelsDateTimeRelatesToTypeToJSON(value?: VTApiPlaneraResaCoreModelsDateTimeRelatesToType | null): any {
    return value as any;
}

