/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsCoordinateApiModel } from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import {
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsCoordinateApiModel';
import type { VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel';

/**
 * Information about a service journey.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel {
    /**
     * 16-digit Västtrafik service journey gid that the trip leg is a part of.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    gid?: string | null;
    /**
     * A description of the direction.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    direction?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    directionDetails?: VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    line?: VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel;
    /**
     * The coordinates on the service journey.
     * @type {Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    serviceJourneyCoordinates?: Array<VTApiPlaneraResaWebV4ModelsCoordinateApiModel> | null;
    /**
     * All calls on the service journey.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel
     */
    callsOnServiceJourney?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel> | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': !exists(json, 'gid') ? undefined : json['gid'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'directionDetails': !exists(json, 'directionDetails') ? undefined : VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON(json['directionDetails']),
        'line': !exists(json, 'line') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModelFromJSON(json['line']),
        'serviceJourneyCoordinates': !exists(json, 'serviceJourneyCoordinates') ? undefined : (json['serviceJourneyCoordinates'] === null ? null : (json['serviceJourneyCoordinates'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelFromJSON)),
        'callsOnServiceJourney': !exists(json, 'callsOnServiceJourney') ? undefined : (json['callsOnServiceJourney'] === null ? null : (json['callsOnServiceJourney'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelFromJSON)),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'direction': value.direction,
        'directionDetails': VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON(value.directionDetails),
        'line': VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModelToJSON(value.line),
        'serviceJourneyCoordinates': value.serviceJourneyCoordinates === undefined ? undefined : (value.serviceJourneyCoordinates === null ? null : (value.serviceJourneyCoordinates as Array<any>).map(VTApiPlaneraResaWebV4ModelsCoordinateApiModelToJSON)),
        'callsOnServiceJourney': value.callsOnServiceJourney === undefined ? undefined : (value.callsOnServiceJourney === null ? null : (value.callsOnServiceJourney as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModelToJSON)),
    };
}

