/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel';
import type { VTApiPlaneraResaWebV4ModelsNoteApiModel } from './VTApiPlaneraResaWebV4ModelsNoteApiModel';
import {
    VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsNoteApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsNoteApiModel';

/**
 * Information about a call on the trip leg.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel {
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
     */
    stopPoint: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel;
    /**
     * The planned time of the call in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
     */
    plannedTime: string;
    /**
     * The estimated time of the call in RFC 3339 format.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
     */
    estimatedTime?: string | null;
    /**
     * The best known time of the call in RFC 3339 format. Is EstimatedTime if exists, otherwise PlannedTime.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
     */
    readonly estimatedOtherwisePlannedTime?: string | null;
    /**
     * An ordered list (most important first) of notes related to the call.
     * @type {Array<VTApiPlaneraResaWebV4ModelsNoteApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel
     */
    notes?: Array<VTApiPlaneraResaWebV4ModelsNoteApiModel> | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stopPoint" in value;
    isInstance = isInstance && "plannedTime" in value;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stopPoint': VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSON(json['stopPoint']),
        'plannedTime': json['plannedTime'],
        'estimatedTime': !exists(json, 'estimatedTime') ? undefined : json['estimatedTime'],
        'estimatedOtherwisePlannedTime': !exists(json, 'estimatedOtherwisePlannedTime') ? undefined : json['estimatedOtherwisePlannedTime'],
        'notes': !exists(json, 'notes') ? undefined : (json['notes'] === null ? null : (json['notes'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSON)),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsCallApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stopPoint': VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelToJSON(value.stopPoint),
        'plannedTime': value.plannedTime,
        'estimatedTime': value.estimatedTime,
        'notes': value.notes === undefined ? undefined : (value.notes === null ? null : (value.notes as Array<any>).map(VTApiPlaneraResaWebV4ModelsNoteApiModelToJSON)),
    };
}

