/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the source from which the occupancy information originate.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsOccupancyInformationSource = {
    Prediction: 'prediction',
    Realtime: 'realtime'
} as const;
export type VTApiPlaneraResaWebV4ModelsOccupancyInformationSource = typeof VTApiPlaneraResaWebV4ModelsOccupancyInformationSource[keyof typeof VTApiPlaneraResaWebV4ModelsOccupancyInformationSource];


export function VTApiPlaneraResaWebV4ModelsOccupancyInformationSourceFromJSON(json: any): VTApiPlaneraResaWebV4ModelsOccupancyInformationSource {
    return VTApiPlaneraResaWebV4ModelsOccupancyInformationSourceFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsOccupancyInformationSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsOccupancyInformationSource {
    return json as VTApiPlaneraResaWebV4ModelsOccupancyInformationSource;
}

export function VTApiPlaneraResaWebV4ModelsOccupancyInformationSourceToJSON(value?: VTApiPlaneraResaWebV4ModelsOccupancyInformationSource | null): any {
    return value as any;
}

