/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies a maneuver to be executed for a link segment.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver = {
    None: 'none',
    From: 'from',
    To: 'to',
    On: 'on',
    Left: 'left',
    Right: 'right',
    Keepleft: 'keepleft',
    Keepright: 'keepright',
    Halfleft: 'halfleft',
    Halfright: 'halfright',
    Keephalfleft: 'keephalfleft',
    Keephalfright: 'keephalfright',
    Sharpleft: 'sharpleft',
    Sharpright: 'sharpright',
    Keepsharpleft: 'keepsharpleft',
    Keepsharpright: 'keepsharpright',
    Straight: 'straight',
    Uturn: 'uturn',
    Enter: 'enter',
    Leave: 'leave',
    Enterroundabout: 'enterroundabout',
    Stayinroundabout: 'stayinroundabout',
    Leaveroundabout: 'leaveroundabout',
    Enterferry: 'enterferry',
    Leaveferry: 'leaveferry',
    Changehighway: 'changehighway',
    Checkinferry: 'checkinferry',
    Checkoutferry: 'checkoutferry',
    Elevator: 'elevator',
    Elevatordown: 'elevatordown',
    Elevatorup: 'elevatorup',
    Escalator: 'escalator',
    Escalatordown: 'escalatordown',
    Escalatorup: 'escalatorup',
    Stairs: 'stairs',
    Stairsdown: 'stairsdown',
    Stairsup: 'stairsup'
} as const;
export type VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver = typeof VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver[keyof typeof VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver];


export function VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSON(json: any): VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver {
    return VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver {
    return json as VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver;
}

export function VTApiPlaneraResaWebV4ModelsLinkSegmentManeuverToJSON(value?: VTApiPlaneraResaWebV4ModelsLinkSegmentManeuver | null): any {
    return value as any;
}

