/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A subset of TransportMode
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsJourneyTransportMode = {
    Tram: 'tram',
    Bus: 'bus',
    Ferry: 'ferry',
    Train: 'train',
    Taxi: 'taxi',
    Walk: 'walk',
    Bike: 'bike',
    Car: 'car'
} as const;
export type VTApiPlaneraResaWebV4ModelsJourneyTransportMode = typeof VTApiPlaneraResaWebV4ModelsJourneyTransportMode[keyof typeof VTApiPlaneraResaWebV4ModelsJourneyTransportMode];


export function VTApiPlaneraResaWebV4ModelsJourneyTransportModeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyTransportMode {
    return VTApiPlaneraResaWebV4ModelsJourneyTransportModeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyTransportModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyTransportMode {
    return json as VTApiPlaneraResaWebV4ModelsJourneyTransportMode;
}

export function VTApiPlaneraResaWebV4ModelsJourneyTransportModeToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyTransportMode | null): any {
    return value as any;
}

