/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsAreaType } from './VTApiPlaneraResaWebV4ModelsAreaType';
import {
    VTApiPlaneraResaWebV4ModelsAreaTypeFromJSON,
    VTApiPlaneraResaWebV4ModelsAreaTypeFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsAreaTypeToJSON,
} from './VTApiPlaneraResaWebV4ModelsAreaType';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel';
import type { VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel } from './VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel';
import {
    VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel';
import type { VTApiPlaneraResaWebV4ModelsTimeLimitation } from './VTApiPlaneraResaWebV4ModelsTimeLimitation';
import {
    VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSON,
    VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsTimeLimitationToJSON,
} from './VTApiPlaneraResaWebV4ModelsTimeLimitation';
import type { VTApiPlaneraResaWebV4ModelsTravellerCategory } from './VTApiPlaneraResaWebV4ModelsTravellerCategory';
import {
    VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSON,
    VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsTravellerCategoryToJSON,
} from './VTApiPlaneraResaWebV4ModelsTravellerCategory';

/**
 * Information about a ticket suggestion.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
    /**
     * The product id.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    productId?: number;
    /**
     * The product name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    productName?: string | null;
    /**
     * The product type.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    productType?: number;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsTravellerCategory}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    travellerCategory?: VTApiPlaneraResaWebV4ModelsTravellerCategory;
    /**
     * The product price in SEK.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    priceInSek?: number;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    timeValidity?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsTimeLimitation}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    timeLimitation?: VTApiPlaneraResaWebV4ModelsTimeLimitation;
    /**
     * A list of the channels that sell the product.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    saleChannels?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModel> | null;
    /**
     * A list of the valid zones for the ticket.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    validZones?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    productInstanceType?: VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    punchConfiguration?: VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel;
    /**
     * Used to get ticket offer.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    offerSpecification?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsAreaType}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel
     */
    areaType?: VTApiPlaneraResaWebV4ModelsAreaType;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'productName': !exists(json, 'productName') ? undefined : json['productName'],
        'productType': !exists(json, 'productType') ? undefined : json['productType'],
        'travellerCategory': !exists(json, 'travellerCategory') ? undefined : VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSON(json['travellerCategory']),
        'priceInSek': !exists(json, 'priceInSek') ? undefined : json['priceInSek'],
        'timeValidity': !exists(json, 'timeValidity') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelFromJSON(json['timeValidity']),
        'timeLimitation': !exists(json, 'timeLimitation') ? undefined : VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSON(json['timeLimitation']),
        'saleChannels': !exists(json, 'saleChannels') ? undefined : (json['saleChannels'] === null ? null : (json['saleChannels'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelFromJSON)),
        'validZones': !exists(json, 'validZones') ? undefined : (json['validZones'] === null ? null : (json['validZones'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelFromJSON)),
        'productInstanceType': !exists(json, 'productInstanceType') ? undefined : VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModelFromJSON(json['productInstanceType']),
        'punchConfiguration': !exists(json, 'punchConfiguration') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSON(json['punchConfiguration']),
        'offerSpecification': !exists(json, 'offerSpecification') ? undefined : json['offerSpecification'],
        'areaType': !exists(json, 'areaType') ? undefined : VTApiPlaneraResaWebV4ModelsAreaTypeFromJSON(json['areaType']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'productName': value.productName,
        'productType': value.productType,
        'travellerCategory': VTApiPlaneraResaWebV4ModelsTravellerCategoryToJSON(value.travellerCategory),
        'priceInSek': value.priceInSek,
        'timeValidity': VTApiPlaneraResaWebV4ModelsJourneyDetailsTimeValidityApiModelToJSON(value.timeValidity),
        'timeLimitation': VTApiPlaneraResaWebV4ModelsTimeLimitationToJSON(value.timeLimitation),
        'saleChannels': value.saleChannels === undefined ? undefined : (value.saleChannels === null ? null : (value.saleChannels as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsChannelApiModelToJSON)),
        'validZones': value.validZones === undefined ? undefined : (value.validZones === null ? null : (value.validZones as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsZoneApiModelToJSON)),
        'productInstanceType': VTApiPlaneraResaWebV4ModelsProductInstanceTypeApiModelToJSON(value.productInstanceType),
        'punchConfiguration': VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelToJSON(value.punchConfiguration),
        'offerSpecification': value.offerSpecification,
        'areaType': VTApiPlaneraResaWebV4ModelsAreaTypeToJSON(value.areaType),
    };
}

