/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel {
    /**
     * The 16-digit Västtrafik gid of the stop point.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    gid: string;
    /**
     * The stop point name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    name: string;
    /**
     * The platform of the stop point.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    platform?: string | null;
    /**
     * The latitude coordinate of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    latitude?: number | null;
    /**
     * The longitude coordinate of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    longitude?: number | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel
     */
    stopArea?: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gid" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': json['gid'],
        'name': json['name'],
        'platform': !exists(json, 'platform') ? undefined : json['platform'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'stopArea': !exists(json, 'stopArea') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSON(json['stopArea']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopPointApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'name': value.name,
        'platform': value.platform,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'stopArea': VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelToJSON(value.stopArea),
    };
}

