/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The severity of a message.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsSeverity = {
    Unknown: 'unknown',
    Low: 'low',
    Normal: 'normal',
    High: 'high'
} as const;
export type VTApiPlaneraResaWebV4ModelsSeverity = typeof VTApiPlaneraResaWebV4ModelsSeverity[keyof typeof VTApiPlaneraResaWebV4ModelsSeverity];


export function VTApiPlaneraResaWebV4ModelsSeverityFromJSON(json: any): VTApiPlaneraResaWebV4ModelsSeverity {
    return VTApiPlaneraResaWebV4ModelsSeverityFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsSeverity {
    return json as VTApiPlaneraResaWebV4ModelsSeverity;
}

export function VTApiPlaneraResaWebV4ModelsSeverityToJSON(value?: VTApiPlaneraResaWebV4ModelsSeverity | null): any {
    return value as any;
}

