/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModel';
import type { VTApiPlaneraResaWebV4ModelsPaginationLinks } from './VTApiPlaneraResaWebV4ModelsPaginationLinks';
import {
    VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSON,
    VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsPaginationLinksToJSON,
} from './VTApiPlaneraResaWebV4ModelsPaginationLinks';
import type { VTApiPlaneraResaWebV4ModelsPaginationProperties } from './VTApiPlaneraResaWebV4ModelsPaginationProperties';
import {
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSON,
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesToJSON,
} from './VTApiPlaneraResaWebV4ModelsPaginationProperties';

/**
 * The response to a get departures request, includes the results and pagination information.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse {
    /**
     * The results.
     * @type {Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse
     */
    results?: Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsPaginationProperties}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse
     */
    pagination?: VTApiPlaneraResaWebV4ModelsPaginationProperties;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsPaginationLinks}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse
     */
    links?: VTApiPlaneraResaWebV4ModelsPaginationLinks;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponseFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponseFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : (json['results'] === null ? null : (json['results'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModelFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSON(json['pagination']),
        'links': !exists(json, 'links') ? undefined : VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSON(json['links']),
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponseToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetDeparturesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : (value.results === null ? null : (value.results as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsDepartureApiModelToJSON)),
        'pagination': VTApiPlaneraResaWebV4ModelsPaginationPropertiesToJSON(value.pagination),
        'links': VTApiPlaneraResaWebV4ModelsPaginationLinksToJSON(value.links),
    };
}

