/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel';
import type { VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';

/**
 * Information about a service journey of a departure or arrival.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel {
    /**
     * 16-digit Västtrafik service journey gid.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
     */
    gid: string;
    /**
     * A description of the origin.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
     */
    origin?: string | null;
    /**
     * A description of the direction.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
     */
    direction?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
     */
    directionDetails?: VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel
     */
    line?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gid" in value;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': json['gid'],
        'origin': !exists(json, 'origin') ? undefined : json['origin'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'directionDetails': !exists(json, 'directionDetails') ? undefined : VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON(json['directionDetails']),
        'line': !exists(json, 'line') ? undefined : VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelFromJSON(json['line']),
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsServiceJourneyApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'origin': value.origin,
        'direction': value.direction,
        'directionDetails': VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON(value.directionDetails),
        'line': VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsLineApiModelToJSON(value.line),
    };
}

