/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Different types of traveller category.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsTravellerCategory = {
    Unknown: 'unknown',
    Adult: 'adult',
    Youth: 'youth'
} as const;
export type VTApiPlaneraResaWebV4ModelsTravellerCategory = typeof VTApiPlaneraResaWebV4ModelsTravellerCategory[keyof typeof VTApiPlaneraResaWebV4ModelsTravellerCategory];


export function VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSON(json: any): VTApiPlaneraResaWebV4ModelsTravellerCategory {
    return VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsTravellerCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsTravellerCategory {
    return json as VTApiPlaneraResaWebV4ModelsTravellerCategory;
}

export function VTApiPlaneraResaWebV4ModelsTravellerCategoryToJSON(value?: VTApiPlaneraResaWebV4ModelsTravellerCategory | null): any {
    return value as any;
}

