/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents time limitations for a ticket.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsTimeLimitation = {
    Unknown: 'unknown',
    Heltid: 'heltid',
    Lagtrafik: 'lagtrafik',
    Skolkort04till19: 'skolkort04till19',
    Skolkort04till22: 'skolkort04till22',
    Skolkort04till1930: 'skolkort04till1930',
    Fritid100: 'fritid100',
    Fritidkomplement: 'fritidkomplement',
    Fritidvardag19till22: 'fritidvardag19till22',
    Fritidvardag14till24: 'fritidvardag14till24',
    Fritidkvallhelg: 'fritidkvallhelg',
    Fritidkvallhelglov: 'fritidkvallhelglov',
    Fritidjulsommarlov: 'fritidjulsommarlov',
    Fritidale: 'fritidale'
} as const;
export type VTApiPlaneraResaWebV4ModelsTimeLimitation = typeof VTApiPlaneraResaWebV4ModelsTimeLimitation[keyof typeof VTApiPlaneraResaWebV4ModelsTimeLimitation];


export function VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSON(json: any): VTApiPlaneraResaWebV4ModelsTimeLimitation {
    return VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsTimeLimitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsTimeLimitation {
    return json as VTApiPlaneraResaWebV4ModelsTimeLimitation;
}

export function VTApiPlaneraResaWebV4ModelsTimeLimitationToJSON(value?: VTApiPlaneraResaWebV4ModelsTimeLimitation | null): any {
    return value as any;
}

