/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel } from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel';
import type { VTApiPlaneraResaWebV4ModelsPaginationLinks } from './VTApiPlaneraResaWebV4ModelsPaginationLinks';
import {
    VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSON,
    VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsPaginationLinksToJSON,
} from './VTApiPlaneraResaWebV4ModelsPaginationLinks';
import type { VTApiPlaneraResaWebV4ModelsPaginationProperties } from './VTApiPlaneraResaWebV4ModelsPaginationProperties';
import {
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSON,
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsPaginationPropertiesToJSON,
} from './VTApiPlaneraResaWebV4ModelsPaginationProperties';

/**
 * The response to a get arrivals request, includes the results and pagination information.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse
 */
export interface VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse {
    /**
     * The results.
     * @type {Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse
     */
    results?: Array<VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsPaginationProperties}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse
     */
    pagination?: VTApiPlaneraResaWebV4ModelsPaginationProperties;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsPaginationLinks}
     * @memberof VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse
     */
    links?: VTApiPlaneraResaWebV4ModelsPaginationLinks;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponseFromJSON(json: any): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse {
    return VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponseFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : (json['results'] === null ? null : (json['results'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModelFromJSON)),
        'pagination': !exists(json, 'pagination') ? undefined : VTApiPlaneraResaWebV4ModelsPaginationPropertiesFromJSON(json['pagination']),
        'links': !exists(json, 'links') ? undefined : VTApiPlaneraResaWebV4ModelsPaginationLinksFromJSON(json['links']),
    };
}

export function VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponseToJSON(value?: VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsGetArrivalsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : (value.results === null ? null : (value.results as Array<any>).map(VTApiPlaneraResaWebV4ModelsDeparturesAndArrivalsArrivalApiModelToJSON)),
        'pagination': VTApiPlaneraResaWebV4ModelsPaginationPropertiesToJSON(value.pagination),
        'links': VTApiPlaneraResaWebV4ModelsPaginationLinksToJSON(value.links),
    };
}

