/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the different types of location.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsLocationType = {
    Unknown: 'unknown',
    Stoparea: 'stoparea',
    Stoppoint: 'stoppoint',
    Address: 'address',
    Pointofinterest: 'pointofinterest',
    Metastation: 'metastation'
} as const;
export type VTApiPlaneraResaWebV4ModelsLocationType = typeof VTApiPlaneraResaWebV4ModelsLocationType[keyof typeof VTApiPlaneraResaWebV4ModelsLocationType];


export function VTApiPlaneraResaWebV4ModelsLocationTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsLocationType {
    return VTApiPlaneraResaWebV4ModelsLocationTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsLocationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsLocationType {
    return json as VTApiPlaneraResaWebV4ModelsLocationType;
}

export function VTApiPlaneraResaWebV4ModelsLocationTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsLocationType | null): any {
    return value as any;
}

