/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneysLineApiModel } from './VTApiPlaneraResaWebV4ModelsJourneysLineApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneysLineApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneysLineApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneysLineApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneysLineApiModel';

/**
 * Information about a service journey of a departure or arrival.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
    /**
     * 16-digit Västtrafik service journey gid.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
     */
    gid: string;
    /**
     * A description of the direction.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
     */
    direction?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
     */
    directionDetails?: VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel;
    /**
     * Västtrafik service journey number that the trip leg is a part of.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
     */
    number?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneysLineApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel
     */
    line?: VTApiPlaneraResaWebV4ModelsJourneysLineApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gid" in value;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': json['gid'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'directionDetails': !exists(json, 'directionDetails') ? undefined : VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelFromJSON(json['directionDetails']),
        'number': !exists(json, 'number') ? undefined : json['number'],
        'line': !exists(json, 'line') ? undefined : VTApiPlaneraResaWebV4ModelsJourneysLineApiModelFromJSON(json['line']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'direction': value.direction,
        'directionDetails': VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModelToJSON(value.directionDetails),
        'number': value.number,
        'line': VTApiPlaneraResaWebV4ModelsJourneysLineApiModelToJSON(value.line),
    };
}

