/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel';

/**
 * Represents punch configuration.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel {
    /**
     * Punch quota of a single ticket.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel
     */
    quota?: number | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel
     */
    duration?: VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quota': !exists(json, 'quota') ? undefined : json['quota'],
        'duration': !exists(json, 'duration') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelFromJSON(json['duration']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quota': value.quota,
        'duration': VTApiPlaneraResaWebV4ModelsJourneyDetailsPunchConfigurationDurationApiModelToJSON(value.duration),
    };
}

