/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A subset of LocationType
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsLocationByTextType = {
    Stoparea: 'stoparea',
    Address: 'address',
    Pointofinterest: 'pointofinterest',
    Metastation: 'metastation'
} as const;
export type VTApiPlaneraResaWebV4ModelsLocationByTextType = typeof VTApiPlaneraResaWebV4ModelsLocationByTextType[keyof typeof VTApiPlaneraResaWebV4ModelsLocationByTextType];


export function VTApiPlaneraResaWebV4ModelsLocationByTextTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsLocationByTextType {
    return VTApiPlaneraResaWebV4ModelsLocationByTextTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsLocationByTextTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsLocationByTextType {
    return json as VTApiPlaneraResaWebV4ModelsLocationByTextType;
}

export function VTApiPlaneraResaWebV4ModelsLocationByTextTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsLocationByTextType | null): any {
    return value as any;
}

