/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VTApiPlaneraResaCoreModelsPositionTransportMode = {
    Tram: 'tram',
    Bus: 'bus',
    Ferry: 'ferry',
    Train: 'train',
    Taxi: 'taxi'
} as const;
export type VTApiPlaneraResaCoreModelsPositionTransportMode = typeof VTApiPlaneraResaCoreModelsPositionTransportMode[keyof typeof VTApiPlaneraResaCoreModelsPositionTransportMode];


export function VTApiPlaneraResaCoreModelsPositionTransportModeFromJSON(json: any): VTApiPlaneraResaCoreModelsPositionTransportMode {
    return VTApiPlaneraResaCoreModelsPositionTransportModeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaCoreModelsPositionTransportModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaCoreModelsPositionTransportMode {
    return json as VTApiPlaneraResaCoreModelsPositionTransportMode;
}

export function VTApiPlaneraResaCoreModelsPositionTransportModeToJSON(value?: VTApiPlaneraResaCoreModelsPositionTransportMode | null): any {
    return value as any;
}

