/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Different types of age types for a product.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsAgeType = {
    Adult: 'adult',
    Youth: 'youth',
    Senior: 'senior',
    Schoolyouth: 'schoolyouth',
    Other: 'other'
} as const;
export type VTApiPlaneraResaWebV4ModelsAgeType = typeof VTApiPlaneraResaWebV4ModelsAgeType[keyof typeof VTApiPlaneraResaWebV4ModelsAgeType];


export function VTApiPlaneraResaWebV4ModelsAgeTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsAgeType {
    return VTApiPlaneraResaWebV4ModelsAgeTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsAgeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsAgeType {
    return json as VTApiPlaneraResaWebV4ModelsAgeType;
}

export function VTApiPlaneraResaWebV4ModelsAgeTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsAgeType | null): any {
    return value as any;
}

