/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsSeverity } from './VTApiPlaneraResaWebV4ModelsSeverity';
import {
    VTApiPlaneraResaWebV4ModelsSeverityFromJSON,
    VTApiPlaneraResaWebV4ModelsSeverityFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsSeverityToJSON,
} from './VTApiPlaneraResaWebV4ModelsSeverity';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsNoteApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsNoteApiModel {
    /**
     * The type of the note.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsNoteApiModel
     */
    type?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsSeverity}
     * @memberof VTApiPlaneraResaWebV4ModelsNoteApiModel
     */
    severity?: VTApiPlaneraResaWebV4ModelsSeverity;
    /**
     * The note message.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsNoteApiModel
     */
    text?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsNoteApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsNoteApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsNoteApiModel {
    return VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsNoteApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsNoteApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'severity': !exists(json, 'severity') ? undefined : VTApiPlaneraResaWebV4ModelsSeverityFromJSON(json['severity']),
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function VTApiPlaneraResaWebV4ModelsNoteApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsNoteApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'severity': VTApiPlaneraResaWebV4ModelsSeverityToJSON(value.severity),
        'text': value.text,
    };
}

