/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The different kinds of detailed information that could be included in a get arrival details request.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType = {
    Servicejourneycalls: 'servicejourneycalls',
    Servicejourneycoordinates: 'servicejourneycoordinates'
} as const;
export type VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType = typeof VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType[keyof typeof VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType];


export function VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeTypeFromJSON(json: any): VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType {
    return VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeTypeFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType {
    return json as VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType;
}

export function VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeTypeToJSON(value?: VTApiPlaneraResaWebV4ModelsArrivalDetailsIncludeType | null): any {
    return value as any;
}

