/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
    /**
     * The 16-digit Västtrafik gid of the stop area.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    gid?: string | null;
    /**
     * The stop area name.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    name?: string | null;
    /**
     * The latitude of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    latitude?: number;
    /**
     * The longitude of the stop point.
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    longitude?: number;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    tariffZone1?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel
     */
    tariffZone2?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gid': !exists(json, 'gid') ? undefined : json['gid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'tariffZone1': !exists(json, 'tariffZone1') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON(json['tariffZone1']),
        'tariffZone2': !exists(json, 'tariffZone2') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON(json['tariffZone2']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsStopAreaApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gid': value.gid,
        'name': value.name,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'tariffZone1': VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON(value.tariffZone1),
        'tariffZone2': VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON(value.tariffZone2),
    };
}

