/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Different types of products.
 * @export
 */
export const VTApiPlaneraResaWebV4ModelsProductTypeEnum = {
    Single: 'single',
    Period: 'period',
    Shortterm: 'shortterm',
    School: 'school',
    Event: 'event',
    Flex: 'flex',
    Seasonal: 'seasonal'
} as const;
export type VTApiPlaneraResaWebV4ModelsProductTypeEnum = typeof VTApiPlaneraResaWebV4ModelsProductTypeEnum[keyof typeof VTApiPlaneraResaWebV4ModelsProductTypeEnum];


export function VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSON(json: any): VTApiPlaneraResaWebV4ModelsProductTypeEnum {
    return VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsProductTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsProductTypeEnum {
    return json as VTApiPlaneraResaWebV4ModelsProductTypeEnum;
}

export function VTApiPlaneraResaWebV4ModelsProductTypeEnumToJSON(value?: VTApiPlaneraResaWebV4ModelsProductTypeEnum | null): any {
    return value as any;
}

