/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsAgeType } from './VTApiPlaneraResaWebV4ModelsAgeType';
import {
    VTApiPlaneraResaWebV4ModelsAgeTypeFromJSON,
    VTApiPlaneraResaWebV4ModelsAgeTypeFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsAgeTypeToJSON,
} from './VTApiPlaneraResaWebV4ModelsAgeType';

/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel {
    /**
     * 
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    productId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    validityLength?: number;
    /**
     * 
     * @type {number}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    itemPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    offerSpecification?: string | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsAgeType}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    ageType?: VTApiPlaneraResaWebV4ModelsAgeType;
    /**
     * 
     * @type {Array<string>}
     * @memberof VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel
     */
    zoneIds?: Array<string> | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel {
    return VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'validityLength': !exists(json, 'validityLength') ? undefined : json['validityLength'],
        'itemPrice': !exists(json, 'itemPrice') ? undefined : json['itemPrice'],
        'offerSpecification': !exists(json, 'offerSpecification') ? undefined : json['offerSpecification'],
        'ageType': !exists(json, 'ageType') ? undefined : VTApiPlaneraResaWebV4ModelsAgeTypeFromJSON(json['ageType']),
        'zoneIds': !exists(json, 'zoneIds') ? undefined : json['zoneIds'],
    };
}

export function VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'validityLength': value.validityLength,
        'itemPrice': value.itemPrice,
        'offerSpecification': value.offerSpecification,
        'ageType': VTApiPlaneraResaWebV4ModelsAgeTypeToJSON(value.ageType),
        'zoneIds': value.zoneIds,
    };
}

