/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel';
import type { VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel } from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel';
import {
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel';
import type { VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel } from './VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel';
import {
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSON,
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSONTyped,
    VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelToJSON,
} from './VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel';

/**
 * Detailed information about a journey.
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel {
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    departureAccessLink?: VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel;
    /**
     * Detailed information, including stops, about the trip legs.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    tripLegs?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel> | null;
    /**
     * A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    connectionLinks?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    arrivalAccessLink?: VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    destinationLink?: VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    ticketSuggestionsResult?: VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel;
    /**
     * The tariff zones that the journey traverses.
     * @type {Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel>}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    tariffZones?: Array<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel> | null;
    /**
     * 
     * @type {VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel
     */
    occupancy?: VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departureAccessLink': !exists(json, 'departureAccessLink') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModelFromJSON(json['departureAccessLink']),
        'tripLegs': !exists(json, 'tripLegs') ? undefined : (json['tripLegs'] === null ? null : (json['tripLegs'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelFromJSON)),
        'connectionLinks': !exists(json, 'connectionLinks') ? undefined : (json['connectionLinks'] === null ? null : (json['connectionLinks'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModelFromJSON)),
        'arrivalAccessLink': !exists(json, 'arrivalAccessLink') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModelFromJSON(json['arrivalAccessLink']),
        'destinationLink': !exists(json, 'destinationLink') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModelFromJSON(json['destinationLink']),
        'ticketSuggestionsResult': !exists(json, 'ticketSuggestionsResult') ? undefined : VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModelFromJSON(json['ticketSuggestionsResult']),
        'tariffZones': !exists(json, 'tariffZones') ? undefined : (json['tariffZones'] === null ? null : (json['tariffZones'] as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelFromJSON)),
        'occupancy': !exists(json, 'occupancy') ? undefined : VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelFromJSON(json['occupancy']),
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departureAccessLink': VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModelToJSON(value.departureAccessLink),
        'tripLegs': value.tripLegs === undefined ? undefined : (value.tripLegs === null ? null : (value.tripLegs as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModelToJSON)),
        'connectionLinks': value.connectionLinks === undefined ? undefined : (value.connectionLinks === null ? null : (value.connectionLinks as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModelToJSON)),
        'arrivalAccessLink': VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModelToJSON(value.arrivalAccessLink),
        'destinationLink': VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModelToJSON(value.destinationLink),
        'ticketSuggestionsResult': VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModelToJSON(value.ticketSuggestionsResult),
        'tariffZones': value.tariffZones === undefined ? undefined : (value.tariffZones === null ? null : (value.tariffZones as Array<any>).map(VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModelToJSON)),
        'occupancy': VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModelToJSON(value.occupancy),
    };
}

