/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel {
    /**
     * An Id for matching this existingTicket with ticketValidityApiModel in response.
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel
     */
    id?: string | null;
    /**
     * From TicketSuggestionApiModel
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel
     */
    offerSpecification?: string | null;
    /**
     * Must be specified in RFC 3339 format
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel
     */
    timeOfIssue?: string | null;
    /**
     * Must be specified in RFC 3339 format
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel
     */
    timeOfActivation?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'offerSpecification': !exists(json, 'offerSpecification') ? undefined : json['offerSpecification'],
        'timeOfIssue': !exists(json, 'timeOfIssue') ? undefined : json['timeOfIssue'],
        'timeOfActivation': !exists(json, 'timeOfActivation') ? undefined : json['timeOfActivation'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneyDetailsExistingTicketApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'offerSpecification': value.offerSpecification,
        'timeOfIssue': value.timeOfIssue,
        'timeOfActivation': value.timeOfActivation,
    };
}

