/* tslint:disable */
/* eslint-disable */
/**
 * Planera Resa
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Shortened version of existing reconstruction reference
 * @export
 * @interface VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel
 */
export interface VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel {
    /**
     * 
     * @type {string}
     * @memberof VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel
     */
    shortenedReconstructionRef?: string | null;
}

/**
 * Check if a given object implements the VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel interface.
 */
export function instanceOfVTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModelFromJSON(json: any): VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel {
    return VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModelFromJSONTyped(json, false);
}

export function VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shortenedReconstructionRef': !exists(json, 'shortenedReconstructionRef') ? undefined : json['shortenedReconstructionRef'],
    };
}

export function VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModelToJSON(value?: VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shortenedReconstructionRef': value.shortenedReconstructionRef,
    };
}

