#!/bin/sh
set -e

echo "Assuming curl, yq, npx are available!"

# OpenAPI json file temp path
SLINFO_GEN_TEMP=$(mktemp)

# Fetch
echo "Fetching OpenAPI spec..."
curl -s 'https://raw.githubusercontent.com/trafiklab/openApi-docs/master/resrobot-v21.yaml' | yq -o=json >"$SLINFO_GEN_TEMP"

echo "Generating client..."
npx openapi-typescript-codegen --input "$SLINFO_GEN_TEMP" --output ./src/generated/resrobot

echo "Removing temp OpenAPI json..."
rm "$SLINFO_GEN_TEMP" || echo "(failed temp file removal)"
