// Config
const REALTIME_API_KEY = process.env.SL_REALTIME_API_KEY;
const SITE_ID = process.env.SL_SITE_ID;
const JOURNEY_DIRECTION = Number(process.env.SL_JOURNEY_DIRECTION);
const TIME_WINDOW_MINUTES = Number(process.env.TIME_WINDOW_MINUTES || 20);
const FETCH_INTERVAL_MS = Number(process.env.FETCH_INTERVAL_MS || 15000);
const REFRESH_INTERVAL_MS = Number(process.env.REFRESH_INTERVAL_MS || 5000);

const WALK_TIME_SECONDS = Number(process.env.WALK_TIME_SECONDS || 300);
const RUSH_SECONDS_GAINED = Number(process.env.RUSH_SECONDS_GAINED || 90);

const { log } = require("./log");

log("CONFIG", {
  JOURNEY_DIRECTION,
  TIME_WINDOW_MINUTES,
  FETCH_INTERVAL_MS,
  REFRESH_INTERVAL_MS,
  WALK_TIME_SECONDS,
  RUSH_SECONDS_GAINED,
});

module.exports = {
  REALTIME_API_KEY,
  SITE_ID,
  JOURNEY_DIRECTION,
  TIME_WINDOW_MINUTES,
  FETCH_INTERVAL_MS,
  REFRESH_INTERVAL_MS,
  WALK_TIME_SECONDS,
  RUSH_SECONDS_GAINED,
};
